name: appeducafin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gráficos
  fl_chart: ^1.0.0

  # HTTP / API
  http: ^1.1.0
  dio: ^5.4.0
  retrofit: ^4.0.1
  json_annotation: ^4.9.0

  # Firebase (versões oficiais e compatíveis com intl 0.20.2)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_ui_auth: ^1.10.0
  cloud_firestore: ^5.6.8
  firebase_ui_firestore: ^1.7.1

  # Injeção de dependência
  get_it: ^8.0.3

  # Preview de dispositivos (opcional)
  device_preview: ^1.2.0

  # Localizações (necessário por firebase_ui)
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
