// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZyv8yBbS6UUnz4NgrSb7uwPa2TGtjipw',
    appId: '1:459515423999:web:311d5ecd1e66c669bab0ca',
    messagingSenderId: '459515423999',
    projectId: 'appfacul-2025',
    authDomain: 'appfacul-2025.firebaseapp.com',
    storageBucket: 'appfacul-2025.firebasestorage.app',
    measurementId: 'G-GV8ENCTYKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMWoJyIqfFLzeXyXQNRqPnBv4BQ0MApQ',
    appId: '1:459515423999:android:2d0e383550a449abbab0ca',
    messagingSenderId: '459515423999',
    projectId: 'appfacul-2025',
    storageBucket: 'appfacul-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1C3UntxF5nVBjMIZXvTCBbC72EAaHLo',
    appId: '1:459515423999:ios:94e3bb650e8fd40bbab0ca',
    messagingSenderId: '459515423999',
    projectId: 'appfacul-2025',
    storageBucket: 'appfacul-2025.firebasestorage.app',
    iosBundleId: 'com.example.appeducafin',
  );
}
